### ISSUE TITLE
Data model documentation and/or format

### ISSUE THREAD

**Issue by craigco** [moodysalem/react-tournament-bracket#1]
This is really a question:  Do you have any detail on your data model?  I looked at demo-data.js and there are a lot of fields to the graph.

**Comment by moodysalem** [comment]
Just the react propType shapes but I would love a PR if you have a better model

https://github.com/moodysalem/react-tournament-bracket/blob/gh-pages/src/components/GameShape.jsx

**Comment by craigco** [comment]
I'll give your model a shot and send you a PR if I simplify as I integrate
