### ISSUE TITLE
5 Teams Tournamnet

### ISSUE THREAD

**Issue by juankmarin** [moodysalem/react-tournament-bracket#15]
Hi @moodysalem 

The library allow this kind of brackets?
<img width="724" alt="5 teams" src="https://user-images.githubusercontent.com/12274907/53045664-33128c80-345c-11e9-93ae-21934019c9e3.png">
Thanks

**Comment by moodysalem** [comment]
Yes, this should work fine. There are examples of games with teams that have only one side seeded from another game in the demo
https://moodysalem.github.io/react-tournament-bracket/

The presentation will not be as dense though.
