### ISSUE TITLE
`seed` is not a required prop but generator fails if it is not provided 

### ISSUE THREAD

**Issue by ikovic** [moodysalem/react-tournament-bracket#2]
If you leave the `seed` property of a `Side` undefined, `BracketGenerator` fails on this [line](https://github.com/moodysalem/react-tournament-bracket/blob/gh-pages/src/components/BracketGenerator.jsx#L23).

Since `seed` is not required, maybe you should check for falsy value instead of explicitly checking if it is null? I can open a PR for this if you don't mind.

Worked around this by setting `seed` to null in `Side` object.

**Comment by moodysalem** [comment]
@ikovic I did a PR today that converts the module to TypeScript, so if you're using it in a TypeScript project, you should get type errors if you provide incorrect types. I also saw a place where I was checking seed against `null`, and replaced it with checking if `seed` was truthy
