### ISSUE TITLE
react_controllables_1.default is not a function

### ISSUE THREAD

**Issue by rootblack45** [moodysalem/react-tournament-bracket#3]
using "react-tournament-bracket": "0.2.0"

[image](https://user-images.githubusercontent.com/26060677/39709616-9054043c-5244-11e8-844a-446c35ba4bc7.png)

**Comment by moodysalem** [comment]
Dang, let me work on it. For now please use 0.1.0

**Comment by moodysalem** [comment]
Actually i think I fixed it in 0.2.1 can you try that? Sorry I don’t have better tests

**Comment by rootblack45** [comment]
Got It thanks 💃
