### ISSUE TITLE
Provide @types/react-tournament-bracket

### ISSUE THREAD

**Issue by jasonwr** [moodysalem/react-tournament-bracket#7]
Please provide a **@types/react-tournament-bracket** module so we can do the following:

`npm i @types/react-tournament-bracket`

or

`yarn add @types/react-tournament-bracket`

That way we can apply your module to TypeScript based React-TSX files.

**Comment by moodysalem** [comment]
The types are included in the distribution package - you don't need a separate `@types` package

**Comment by jasonwr** [comment]
Fair enough. Is there code for that demo anywhere? Also what format does the game Parma take? Thanks.

**Comment by moodysalem** [comment]
The code for the demo is on `gh-pages` branch but uses the 0.1.x version of the code. Need to update the demo unfortunately but haven't figured out exactly how i want to do it, will probably add a demo folder to master that uses `create-react-app` and build to `gh-pages` branch. 

The type for the game parameter is described in [model.ts](https://github.com/moodysalem/react-tournament-bracket/blob/master/src/components/model.ts), but I want to make it flat for version 0.3 and would love a PR to change the model
